name: pg_timezone
version: 1.0.0
description: Time zone database and time zone aware DateTime.
repository: https://github.com/insinfo/pg_timezone

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  args: any
  file: '>=6.0.0 <8.0.0'
  glob: ^2.0.0
  lints: ^3.0.0
  logging: ^1.2.0
  test: ^1.16.0
